services:
  vpn:
    image: wg_vpn
    cap_add:
      - NET_ADMIN
    ports:
      - "51820/udp"
    pull_policy: never
  dr_sneaky:
    image: dr_sneaky
    cap_add:
      - NET_ADMIN
    pull_policy: never
#networks:
#  default:
#    ipam:
#      config:
#        - subnet: 10.3.13.0/24
